config/routes.rb
Rails.application.routes.draw do
  
  root  'static_pages#home'
  match '/services',    to: 'static_pages#services',    via: 'get'
  match '/collective',   to: 'static_pages#collective',   via: 'get'
  match '/enquiry', to: 'static_pages#enquiry', via: 'get'
  match '/photos', to: 'static_pages#photos', via: 'get'
  match '/comments', to: 'static_pages#comments', via: 'get'
  match '/qa', to: 'static_pages#qa', via: 'get'
  match '/interesting', to: 'static_pages#interesting', via: 'get'
  match '/documents', to: 'static_pages#documents', via: 'get'
  match '/contacts', to: 'static_pages#contacts', via: 'get'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def services
  end

  def collective
  end

  def enquiry
  end

  def interesting
  end

  def documents
  end

  def contacts
  end

  def comments
  end

  def qa
  end

  def photos
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
		base_title = 'Медицинский центр "Здоровье"'
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<hr>
<p>ООО "Лад" 2016</p

app/views/layouts/_header.html.erb
    <div class="f-nav-bar">
      <div class="f-nav-bar-body">
        <div class="f-nav-bar-title">
          <li><%= link_to ' Медицинский центр "Здоровье"', root_path %></li>
        </div><!-- f-nav-bar-title -->
        <ul class="f-nav">
          
          <li><%= link_to "Услуги", services_path %></li>
          <li><%= link_to "Наш коллектив", collective_path %></li>
          <li><%= link_to "Справки", enquiry_path %></li>
          <li><%= link_to "Отзывы", comments_path %></li>
          <li><%= link_to "Фотогалерея", photos_path %></li>
          <li><%= link_to "Документы", documents_path %></li>
          <li><%= link_to "Это интересно", interesting_path %></li>
          <li><%= link_to "Вопрос-Ответ", qa_path %></li>
          <li><%= link_to "Контакты", contacts_path %></li>

        </ul><!-- f-nav -->
      </div><!-- f-nav-bar-body -->
    </div><!-- f-nav-bar -->

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %> </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<div class="g">
		<div class="g-row">
    		<div class="g-12">
				<%= render 'layouts/header' %>
			</div>
		</div>
	</div>

				
	<div class="container">
		<div class="g">
  			<div class="g-row">
    			<div class="g-12">
					<%= yield %>		
				</div>
			</div>
		</div>
	</div>


	<div class="g">
  		<div class="g-row">
    		<div class="g-12">
				<%= render 'layouts/footer' %>
			</div>
		</div>
	</div>

</body>
</html>

app/views/static_pages/collective.html.erb
    <div class="g-row f-gallery">
    	
    	<div class="g-4 f-gallery-item">
    		<a href="#"><img alt="" src="/assets/kravtsova-241x300.jpg" />
     		<small>Кравцова Лариса Викторовна<br>врач-акушер-гинеколог</small></a>
    	</div><!-- f-gallery-item -->

    	<div class="g-4 f-gallery-item">
    		<a href="#"><img alt="" src="/assets/kulik-241x300.png" />
     		<small>Кулик Елена Николаевна<br>медицинская сестра</small></a>
    	</div><!-- f-gallery-item -->

    	<div class="g-4 f-gallery-item">
    		<a href="#"><img alt="" src="/assets/mazanova-241x300.png" />
     		<small>Мазанова Людмила Николаевна<br>врач педиатр, дерматовенеролог, косметолог</small></a>
        </div><!-- f-gallery-item -->

    </div><!-- f-gallery -->
    <div class="g-row f-gallery">

    	<div class="g-4 f-gallery-item">
    		<a href="#"><img alt="" src="/assets/purin-241x300.png" />
     		<small>Пурин Михаил Михайлович<br>врач невролог, рефлексотерапевт</small></a>
    	</div><!-- f-gallery-item -->

    	<div class="g-4 f-gallery-item">
    		<a href="#"><img alt="" src="/assets/stuzhuk-241x300.png" />
     		<small>Стружук Ольга Юрьевна<br>врач офтальмолог</small></a>
    	</div><!-- f-gallery-item -->

    	<div class="g-4 f-gallery-item">
    		<a href="#"><img alt="" src="/assets/tupitsina-241x300.png" />
     		<small>Тупицина Наталья Викторовна<br>врач функциональной диагностики высшей категории</small></a>
    	</div><!-- f-gallery-item -->
    </div><!-- f-gallery -->
    <div class="g-row f-gallery">

    	<div class="g-4 f-gallery-item">
    		<a href="#"><img alt="" src="/assets/sharipova-241x300.png" />
     		<small>Шарипова Людмила Азаловна<br>врач ультразвуковой диагностики</small></a>
    	</div><!-- f-gallery-item -->

    	<div class="g-4 f-gallery-item">
    		<a href="#"><img alt="" src="/assets/shubina-241x300.png" />
     		<small>Шубина Елена Николаевна<br>врач ультразвуковой диагностики</small></a>
    	</div><!-- f-gallery-item -->

    	<div class="g-4 f-gallery-item">
    		<a href="#"><img alt="" src="/assets/scheka-241x300.png" />
     		<small>Щека Владимир Иванович<br>врач оториноларинолог врач высшей категории</small></a>
    	</div><!-- f-gallery-item -->
    </div><!-- f-gallery -->

    	
    

app/views/static_pages/enquiry.html.erb
 <h1>Справки</h1>

 	<ul>
    	<li>медицинскую справку для ГАИ (водительская комиссия);</li>
    	<li>медицинскую справку для управления маломерными судами;</li>
    	<li>медицинскую справку для поступления в учебные заведения по форме № 086;</li>
    	<li>медицинскую карту ребенка для поступления в сад и школу;</li>
	</ul>

app/views/static_pages/home.html.erb
<p>
	Недавно встретила в центре поселка свою давнюю знакомую и обомлела! Из энергичной симпатяги, с лучистыми голубыми глазами, она превратилась в грузную, болезненного вида женщину, еле передвигавшую отечные ноги. А ведь мы не виделись всего несколько лет. Правда ее неуемная болтливость осталась в неизмененном виде и я долго и терпеливо выслушивала все медицинские диагнозы и заключения, ознакомилась с перечнем препаратов, их дозировкой и побочными эффектами. Да уж!
	Тяжко и грустно, но- такова жизнь и болячки к нам приходят не спрося разрешения, меняя человека до неузнаваемости, лишая всех радостей жизни, а порой и ее самой…И только тогда начинаешь понимать, что здоровье, пожалуй, самое дорогое, что у человека есть, и ни за какие деньги его не купить, если вовремя не обратить внимание на первые звоночки, дающие сигнал о том, что в вашем организме что-то не так! А организм человеческий — штука загадочная, непредсказуемая,индивидуального подхода к себе требующая.
</p>
<p>
	Мне,к сожалению, эта тема близка и понятна, отменным здоровьем похвастать не могу, но вот опыт житейский по борьбе с коварными болячками какой-никакой накоплен, а потому, позволю себе некоторыми соображениями поделиться. Через какие только эксперименты над собой , по совету добрых знакомых, я в свое время не прошла, в поисках волшебной панацеи! По «бабкам» и экстрасенсам бегала, подшивки газеты «ЗОЖ» дотошно изучала, «Гербалайфы» и «Энричи» через себя пропустила, курсы Норбекова по самоисцелению организма посещала, даже восточную методику Рейки освоила! Но энергетические дыры в моем организме так никто и не залатал, а выброшенные на ветер деньги здоровья не прибавили.
</p>
<p>
	Случилось так, что девять лет назад, я была одной из первых пациенток, только что начавшего свою работу в поселке Кавалерово медицинского центра «Здоровье». Подобного рода учреждений в нашем краевом центре на тот период времени было уже множество, а для нашего района -это был смелый эксперимент. Тогда-то мы и познакомились с его владелицей — Мариной Вениаминовной Лада . Человек, далекий от медицины, но при этом очень чуткий и отзывчивый на чужую боль, успешный предприниматель, не один год ведущая процветающий аптечный бизнес, она осознавала насколько будет непросто создать не только достойную материально-техническую базу, главное – сплотить вокруг себя коллектив профессиональных и грамотных людей, команду единомышленников. Ведь врач – профессия, в которой требуется особый талант, такт и интуиция, а доктор, как священник , должен знать о человеке все! Порой отсутствие откровенности и недосказанность могут стоить жизни. Опытный врач, иногда с порога, понимает проблему, с которой к нему человек пришел.Но, к сожалению, в государственных медицинских учреждениях, где очень большой поток пациентов и жесткий график приема больных, доктор не всегда имеет возможность уделить больному достаточно времени, чтобы обстоятельно вникнуть в его проблему. Поэтому изначально главной своей задачей Марина Вениаминовна видела такую организацию труда медицинского персонала своего центра, чтобы все было сделано для удобства и комфорта его пациентов. И спустя годы, можно с полной уверенностью сказать, что все, задуманное этой неравнодушной женщиной, осуществилось! На сегодняшний день медицинский центр «Здоровье» — одно из самых крупных, известных и популярных далеко за пределами Кавалеровского района частных медицинских учреждений. Его пациентами являются жители всех близлежащих районов: Ольгинского, Тернейского, Дальнегорского ,Чугуевского.
</p>
<p>
	За 9 лет существования «Здоровья» Марина Лада сделала очень многое для его оснащения современнейшим медицинским оборудованием, равным которому нет даже в районных больницах .Сейчас в «Здоровье» осуществляют прием 8 различного профиля врачей, с большим стажем работы, огромным профессиональным багажом, высокой квалификацией, многие из них долгое время работали в районной больнице, а опыт врача- практика – бесценен!
</p>
<p>
	Практически с первого дня существования центра «Здоровье» работает там врач-клиницист , терапевт первой категории <strong>Людмила Азаловна Шарипова</strong>.  Кавалерово – родной для нее поселок, поэтому Людмилу Азаловну здесь знают многие, а если учесть, что с 1985 года по 2008г. она проработала в стационаре Кавалеровской Центральной районной больницы врачом-терапевтом, то понятно сколько людей получили помощь от этого грамотного специалиста. Несколько лет подряд Людмила Азаловна совмещала основную работу в районной больнице с терапевтическими консультациями и ультразвуковыми обследованиями пациентов центра. Но с 2008 года она полностью перешла работать в «Здоровье». Богатый практический опыт помогает Людмиле Азаловне грамотно проводить УЗИ внутренних органов, точно выставлять диагнозы и давать четкие, конкретные и действенные рекомендации по дальнейшему лечению. Переход в частную клинику Людмила Азаловна не считает каким-то предательством по отношению к государственной медицине, она – человек, всю себя посвятивший борьбе за человеческую жизнь, считает своим святым долгом быть верной выбранному пути и соблюдать до конца все морально -этические нормы и принципы профессиональной медицины.
</p>
<p>
	<strong>Михаил Михайлович Пурин</strong> – врач- невропатолог — иглорефлексотерапевт, более 30 лет проработавший в Кавалеровской ЦРБ, долгие годы в качестве заведующего неврологическим отделением, человек неординарный, грамотный, увлеченный и ,главное, неравнодушный. Его богатейший опыт работы в здравоохранении, накопленные знания и практические навыки в этой области медицины, позволяют Михаилу Михайловичу добиваться удивительных успехов по реабилитации и излечению больных, в казалось бы, безнадежных ситуациях.
	В разговоре Михаил Михайлович упомянул о том, что, осознавая всю важность и ответственность своего жизненного пути, выбранной им когда-то медицинской специализации, считает себя счастливым, реализовавшимся в своей области человеком, не зря отдавшим столько лет жизни медицине. По сути, его работа – и есть вся его жизнь! Трудно не поверить в искренность этого, уже далеко не молодого, эрудированного и высокопрофессионального человека, видя неподдельный блеск в его глазах. Он, как ребенок, по сей день радуется каждой своей победе над коварными недугами, одолевающими хрупкий человеческий организм. А сколько таких побед было за годы работы – и не сосчитать! Согласитесь, дорогого стоят благодарные отзывы пациентов, которые еще совсем недавно были прикованы к постели, после перенесенного инсульта, были абсолютно беспомощны и слабы, а сегодня собственными ножками пожаловали к доктору на очередной прием.
	Через кавалеровский медицинский центр «Здоровье» за последнее время прошло множество больных, которые в буквальном смысле слова, заново встали на ноги и пошли, после нескольких сеансов иглотерапии у Михаила Михайловича .Комплексно воздействуя на весь организм, иглы восстанавливают его по крупицам: нормализуя кровоток, правильный энерго — обмен, повышают жизненные силы организма, улучшают работу всех органов и систем, устраняют болевой синдром, снимают нервное и мышечное напряжение, помогают буквально каждой клеточке!
</p>
<p>
	<strong>Владимир Иванович Щека</strong> – ЛОР -врач высшей категории. Этого мягкого, тактичного, внимательного доктора в Кавалерово знают не только взрослые, но и малыши. Владимир Иванович много лет ведет прием в районной поликлинике, лечит больных в стационаре, проводит профосмотры, медосмотры в военкомате. Ответственный, безотказный, грамотный, незаменимый специалист и просто душевный, добрый человек Владимир Иванович пользуется заслуженным уважением у всех своих многочисленных коллег и пациентов. Заболеваний уха, горла, носа существует огромное количество, причем, казалось бы, не столь страшные и грозные на первый взгляд, эти заболевания могут давать серьезнейшие осложнения, порой угрожающие жизни человека. Сколько за свою врачебную практику доктору Щеке пришлось извлечь инородных тел из носов и ушей любопытных маленьких экспериментаторов, удалить серных пробок, воспаленных миндалин и аденоидов, подобрать слуховых аппаратов – не сосчитать! Медицина – его призвание, потому выйдя на заслуженный отдых, Владимир Иванович не представляет себя праздно лежащим на диване с пультом от телевизора. Он – на службе! На службе здоровья своих земляков!
</p>
<p>
	Ведет в медицинском центре прием и высококвалифицированный врач-окулист первой категории <strong>Стужук Ольга Юрьевна</strong>.
	Ольга Юрьевна оказывает медицинскую помощь, диагностику и лечение глазных заболеваний. Незря говорится, что глаза – зеркало души, что же будет с этой душой, если она будет смотреть на мир и ничего не видеть? Для ранней диагностики основной причины слепоты- глаукомы, в «Здоровье» проводится измерение внутриглазного давления бесконтактным тонометром. Ольга Юрьевна помогает своим пациентам правильно подобрать очки, линзы, проводит необходимые дополнительные обследования, порекомендует необходимые лекарственные препараты и, если есть необходимость, поможет оформить документы на оперативное лечение или консультацию в краевую клинику. Из-за большого числа пациентов Ольге Юрьевне приходится совмещать работу в районной поликлинике и в медицинском центре, но от этого никуда не уйдешь! К великому сожалению, специалистов в районах края катастрофически не хватает, поэтому на плечи наших докторов ложится огромная нагрузка, но роптать и плакать, считает Ольга Юрьевна- это расписаться в собственном бессилии и пасовать перед проблемами. Врач не имеет права быть слабым!
</p>
<p>
	<strong>Людмила Николаевна Мазанова</strong>— врач-косметолог, Дерматовенеролог высшей категории. Наблюдается в последние годы рост числа разного рода аллергических, вирусных, грибковых заболеваний, затрагивающих и детей, и взрослых. Повсеместное загрязнение окружающей среды, урбанизация и технический прогресс, некачественные продукты питания, одежда, обувь, игрушки китайского производства- оказывают пагубное воздействие на иммунную систему и весь организм . Справиться с потоком кожных заболеваний, урогенитальных инфекций , экземой, лишаями и другой напастью вам поможет Людмила Николаевна.
	За плечами у этой миловидной, стильной женщины большой опыт работы в медицине, в частности, в педиатрии, со специализацией в дерматологии, венерологии и косметологии. Она много лет занимала должность заведующей Кавалеровской детской поликлиникой, вела прием, как врач-педиатр, постоянно училась, совершенствуя свой профессиональный уровень. Сейчас, освободившись от груза административной ответственности и лишней бумажной волокиты, Людмила Николаевна имеет возможность неограниченного творческого подхода к своей работе. К ней на консультацию приезжает очень много иногородних пациентов, это говорит о том, что у доктора безупречная репутация среди бывших больных.
</p>
<p>
	В арсенале медицинского центра – широкие возможности ультразвуковой диагностики. Сегодня это – очень популярный, информативный, достоверный и доступный каждому метод обследования внутренних органов и систем.
	Прием УЗИ в «Здоровье» ведут два высококлассных специалиста:<br>
	Врач ультразвуковой диагностики высшей категории <strong>Шубина Елена Николаевна</strong>.<br>
	Врач ультразвуковой диагностики высшей категории <strong>Тупицына Наталья Викторовна</strong>.<br>
</p>
<p>
	По причине неполадок со здоровьем, мне частенько приходится бывать на периодических осмотрах и консультациях, поэтому с Еленой Николаевной Шубиной я знакома давно. У нее накоплен огромный опыт за годы работы в Центральной районной больнице п.Кавалерово . Бесконечно ей доверяю и искренне уважаю. Она умеет расположить к себе пациента и выходишь после осмотра УЗИ, настроенным только на позитив и выздоровление. Елена Николаевна, так считаю не только я, самый грамотный в районе специалист в области ультразвукового исследования внутренних органов. Она тактична и спокойна с любым, даже непростым больным, старается подробно, в доступной форме изложить человеку, далекому от медицины, суть его проблемы, при этом, все нюансы собственного организма человек имеет возможность видеть на специально устроенном большом мониторе. Вот почему к ней на прием всегда очень много желающих. Большим авторитетом доктор Шубина пользуется далеко за пределами нашего района. Всегда большая запись из числа будущих мамочек, желающих определить пол ребенка, убедиться в отсутствии патологии его развития, во избежание осложнений беременности и родов. В центре «Здоровье» для этого имеется новейшее, великолепное оборудование.
</p>
<p>
	<strong>Наталья Викторовна Тупицына</strong> – приехала в Приморье после окончания Рязанского мединститута и с тех пор работала в районной больнице Кавалерова. Врач высшей категории, человек бесконечно преданный избранному делу, считает медицину своим призванием, своей судьбой и своей любовью. «Это огромная ответственность, но и необыкновенное удовлетворение от возможности помогать людям быть здоровыми»- убеждена Наталья Викторовна. «Ни в коем случае нельзя нас противопоставлять: частную медицину и государственные медицинские учреждения! Мы — в равной ответственности за человеческую жизнь и у нас общая задача – исцелять людей!»
	Наталья Викторовна целых 12 лет занимала ответственный административный пост Зам. Главврача ЦРБ Кавалерово, совмещая эту работу с функциональной диагностикой. Человек тонкий, тактичный, грамотный специалист и просто приятная женщина, она очень легко влилась в мед.коллектив центра «Здоровье». Как отмечают коллеги Натальи Викторовны,с ее приходом связана масса позитивных перемен, найдены новые формы общения между докторами, проводятся тематические конференции, обмен опытом работы. Она непрестанно учится, следит за всеми новинками в области диагностики патологий сердечно-сосудистой системы, превращает работу и общение с пациентами в творческий позитивный процесс. Наталья Викторовна очень довольна своей сегодняшней возможностью , не лимитируя драгоценное время, уделять каждому больному максимум внимания .
</p>

app/views/static_pages/services.html.erb
<h1> Услуги </h1>

<p>
    В медицинский центр могут обратиться как взрослые, так и дети с самыми разнообразными проблемами со здоровьем. Вы можете предварительно записаться на прием к врачу или вызвать специалиста на дом.
</p>
<p>
    В медицинском центре «Здоровье» процедурный кабинет, дневной стационар, осуществляется забор материала для лабораторных анализов. Квалифицированные медицинские сестры с многолетним стажем практической работы окружат Вас заботой и вниманием, профессионально выполнят все медицинские манипуляции.
</p>
<p>
    Можно пройти предрейсовый и послерейсовый осмотр водителей.
</p>
<p>
    В медицинском центре проводятся медицинские комиссии:
    <ul>
        <li>на право ношения и хранения оружия</li>
        <li>на право управления транспортным средством</li>
        <li>предварительный и периодический профосмотр</li>
     </ul
</p>
<p>
    Лечебная помощь оказывается по следующим направлениям:
    <ul>
        <li>Терапия</li>
        <li>Неврология</li>
        <li>Гинекология</li>
        <li>Дерматовенерология</li>
        <li>Глазные болезни</li>
        <li>Отоларингология</li>
        <li>Иглорефлексотерапия</li>
        <li>Урология</li>
        <li>Хирургия</li>
        <li>Педиатрия</li>
    </ul>
</p>
<p>
    В арсенале нашего центра – широкие возможности ультразвуковой и функциональной диагностики.
    Врачи медицинского центра проводят:
    <ul>
        <li>УЗИ сердца (эхокардиография) с цветным доплеровским картированием</li>
        <li>УЗИ сосудов головного мозга (транскраниальная допплерография)</li>
        <li>УЗИ сосудов нижних конечностей</li>
        <li>УЗИ сосудов верхних конечностей</li>
        <li>УЗИ магистральных сосудов шеи (брахиоцефальных сосудов)</li>
        <li>УЗИ органов брюшной полости – печени, желчного пузыря, поджелудочной железы, селезенки</li>
        <li>УЗИ органов забрюшинного пространства, почек, надпочечников.</li>
        <li>УЗИ щитовидной железы с цветным доплеровским картированием</li>
        <li>УЗИ молочных желез с регионарными лимфатическими узлами</li>
        <li>УЗИ поверхностно расположенных структур – образований кожи и подкожно-жировой клетчатки.</li>
        <li>УЗИ лимфатических узлов всех групп.</li>
        <li>УЗИ мочевого пузыря с определением остаточной мочи</li>
        <li>УЗИ предстательной железы</li>
        <li>УЗИ органов мошонки</li>
        <li>УЗИ брюшной аорты и ее ветвей, нижней полой вены и печеночных сосудов</li>
        <li>УЗИ плода в разные сроки беременности</li>
        <li>УЗИ органов малого таза (трансвагинальным и трансабдоминальным методами), определение раннего срока беременности.</li>
        <li>УЗИ суставов</li>
    </ul>
</p>
<p>
    Так же у нас в центре:
    <ul>
        <li>Регистрация и анализ ЭКГ (электрокардиография)</li>
        <li>Суточное мониторирование ЭКГ (ХОЛТЕР)</li>
    </ul>
</p>
<p>
    В «Здоровье» все предусмотрено для удобства посетителей- это и месторасположение, практически в центре поселка, удобная парковка, чистота и уют внутри помещения, вежливые и внимательные администраторы, быстрота и простота оформления на прием, возможность подождать в мягком кресле у телевизора.
</p>
<p>
    Хочется пожелать всем, у кого возникли проблемы со здоровьем, но не хватает свободного времени, приходите в мед.центр «Здоровье», здесь вам гарантированно и оперативно помогут! Берегите себя и своих близких! Цените жизнь- она так хрупка и быстротечна, и чтобы вполне оценить все ее прелести желательно быть здоровым физически и духовно!
</p>
<p>
    Многопрофильный центр «ЗДОРОВЬЕ» за годы работы заслужил высокую оценку пациентов. В нашем центре вас ждут высококвалифицированный медперсонал, опытные врачи высшей и первой категории, имеющие богатейший стаж практической работы.
</p>